### ISSUE TITLE
Riemann getting lot's of error "Connection reset by peer" 

### ISSUE THREAD

**Issue by SanaZulfiqar** [riemann/riemann#1041]
Hi,

We have a riemann setup to get the events from the rabbit queues through the websocket. We have observed lots of errors below

`INFO [2024-05-23 06:47:40,058] worker-1 - riemann.transport.websockets - New websocket subscription to index : address ~= "^sandbox/1(/.+)*$"
INFO [2024-05-23 06:48:07,000] worker-3 - riemann.transport.websockets - Closing websocket  117.20.68.19 index address ~= "^sandbox/1(/.+)*$"
INFO [2024-05-23 06:50:00,449] worker-4 - riemann.transport.websockets - New websocket subscription to index : address ~= "^sandbox/1(/.+)*$"
WARN [2024-05-23 06:50:53,551] defaultEventExecutorGroup-2-1 - riemann.transport.tcp - TCP handler caught
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:283)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:236)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:226)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
WARN [2024-05-23 06:50:53,552] defaultEventExecutorGroup-2-1 - riemann.transport.tcp - TCP handler caught
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:283)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:236)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:226)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
INFO [2024-05-23 06:51:00,442] worker-1 - riemann.transport.websockets - Closing websocket  117.20.68.19 index address ~= "^sandbox/1(/.+)*$"
INFO [2024-05-23 06:51:02,607] worker-3 - riemann.transport.websockets - New websocket subscription to index : address ~= "^sandbox/1(/.+)*$"
`

We are using the Riemann version : 0.3.7
 - OS: "Debian GNU/Linux"

Let me know if you need additional information.
Thanks

**Comment by smortex** [comment]
That look like errors I got before fixing riemann-c-client (which was used by syslog-ng to communicate with Riemann).  If you hit the same problem, [upstream is fixed](https://git.madhouse-project.org/algernon/riemann-c-client/pulls/14), [Debian unstable packages are fixed](https://metadata.ftp-master.debian.org/changelogs//main/r/riemann-c-client/riemann-c-client_1.10.4-4_changelog), but [stable](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1049988) and [oldstable](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1049982) packages still needs to have the fix merged, but the Debian process for doing so is unfortunately beyond my understanding.

You can find the patch to apply here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1049988;filename=riemann-c-client_1.10.4-2.debdiff;msg=19

In my case, I build the fixed package for Debian and Ubuntu in a private GitLab instance form a repository where I applied the above patch and with the following `.gitlab-ci.yml`:

```yaml
variables:
  DEBFULLNAME: 'Romain Tartière'
  DEBEMAIL: 'romain@blogreen.org'
  DEBIAN_FRONTEND: 'noninteractive'
  LIBRIEMANN_CLIENT_VERSION: '1.10.4'

.debian:
  interruptible: true
  script:
    - 'mv /etc/apt/sources.list /etc/apt/sources.list.orig'
    - "awk '{ print $0; if ($1 == \"deb\") { $1 = \"deb-src\"; print $0 } }' < /etc/apt/sources.list.orig > /etc/apt/sources.list"
    - 'apt-get update'
    - 'apt-get install -y --no-install-recommends devscripts'
    - 'apt-get build-dep -y libriemann-client0'
    - 'apt-get source libriemann-client0'
    - 'cp -R patches riemann-c-client-${LIBRIEMANN_CLIENT_VERSION}/debian/'
    - 'cd riemann-c-client-${LIBRIEMANN_CLIENT_VERSION}'
    - 'dch "Fix GnuTLS send/recv"'
    - 'dpkg-buildpackage -us -uc'
  artifacts:
    paths:
      - '*.deb'

buster:
  extends: .debian
  image: debian:buster

bullseye:
  extends: .debian
  image: debian:bullseye

bionic:
  extends: .debian
  image: ubuntu:bionic
  variables:
    LIBRIEMANN_CLIENT_VERSION: '1.9.1'

focal:
  extends: .debian
  image: ubuntu:focal
```
